import React, { useState, useEffect } from 'react';
import { Brand, Programme, BrandPopularityReport as IBrandPopularityReport } from '../../types';
import { safeFetchJson } from '../../lib/apiUtils';
import {
  Layers,
  Calendar,
  Download,
  Copy,
  Check,
  RefreshCw,
  Filter,
  Laptop,
  RotateCcw,
  ExternalLink,
  Store,
} from 'lucide-react';

interface BrandManagementProps {
  programmes?: Programme[];
}

const BRAND_COLORS = [
  '#3b82f6', // blue (ASUS)
  '#6366f1', // indigo (Lenovo)
  '#06b6d4', // cyan (Apple)
  '#f59e0b', // amber (Dell)
  '#10b981', // emerald (Acer)
  '#ec4899', // pink (HP)
  '#8b5cf6', // purple (MSI)
  '#f97316', // orange (Others)
];

export const BrandManagement: React.FC<BrandManagementProps> = ({ programmes = [] }) => {
  const [brands, setBrands] = useState<Brand[]>([]);
  const [allProgrammes, setAllProgrammes] = useState<Programme[]>(programmes);
  const [period, setPeriod] = useState<'weekly' | 'monthly' | 'all'>('weekly');
  const [selectedProgrammeId, setSelectedProgrammeId] = useState<string>('all');
  const [reportData, setReportData] = useState<IBrandPopularityReport | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [isResetting, setIsResetting] = useState<boolean>(false);
  const [copied, setCopied] = useState<boolean>(false);
  const [resetSuccess, setResetSuccess] = useState<boolean>(false);

  useEffect(() => {
    // Load brands catalogue
    safeFetchJson<Brand[]>('/api/brands').then((res) => {
      if (res.ok && Array.isArray(res.data)) {
        setBrands(res.data);
      }
    });

    // Load programmes if not passed via props
    if (programmes.length === 0) {
      safeFetchJson<Programme[]>('/api/programmes').then((res) => {
        if (res.ok && Array.isArray(res.data)) {
          setAllProgrammes(res.data);
        }
      });
    } else {
      setAllProgrammes(programmes);
    }
  }, [programmes]);

  useEffect(() => {
    fetchReport();
  }, [period, selectedProgrammeId]);

  const fetchReport = async () => {
    setIsLoading(true);
    try {
      const queryParams = new URLSearchParams();
      queryParams.set('period', period);
      if (selectedProgrammeId !== 'all') {
        queryParams.set('programme_id', selectedProgrammeId);
      }

      const res = await safeFetchJson<IBrandPopularityReport>(`/api/reports/brand-popularity?${queryParams.toString()}`);
      if (res.ok && res.data) {
        setReportData(res.data);
      }
    } catch (e) {
      console.error('Failed to load brand popularity report', e);
    } finally {
      setIsLoading(false);
    }
  };

  const handleResetToZero = async () => {
    if (!window.confirm('Reset all student laptop popularity picks to 0?')) return;
    setIsResetting(true);
    try {
      const res = await safeFetchJson<{ success: boolean; message: string }>('/api/reports/brand-popularity/reset', {
        method: 'POST',
      });
      if (res.ok) {
        setResetSuccess(true);
        setTimeout(() => setResetSuccess(false), 3000);
        await fetchReport();
      }
    } catch (e) {
      console.error('Failed to reset picks', e);
    } finally {
      setIsResetting(false);
    }
  };

  const handleCopySummary = () => {
    if (!reportData) return;

    const brandBreakdown = reportData.brands
      .map(
        (b, i) =>
          `${i + 1}. ${b.brandName}: ${b.pickCount} picks (${b.percentage}%) | Top Model: ${b.topModel} | Avg Budget: RM ${b.avgBudget.toLocaleString()}`
      )
      .join('\n');

    const summaryText = `📊 UOW COMPUTER ADVISOR - POPULAR PICKS RANKS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Timeframe: ${reportData.periodLabel}
Total Laptops Picked/Recommended: ${reportData.totalPicks}
#1 Most Popular Brand: ${reportData.totalPicks > 0 ? reportData.topBrandName : 'None yet'} (${reportData.topBrandShare}% share)
Top Laptop Model: ${reportData.topModelName}

📈 POPULAR PICKS RANKS:
${brandBreakdown}

Generated by UOW Computer Advisor Decision Support System on ${new Date().toLocaleDateString()}`;

    navigator.clipboard.writeText(summaryText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleExportCSV = () => {
    if (!reportData || !reportData.brands.length) return;

    const headers = ['Rank', 'Brand Name', 'Pick Count', 'Share Percentage (%)', 'Top Picked Model', 'Average Budget (MYR)', 'Growth Rate (%)', 'Programmes'];
    const rows = reportData.brands.map((b, idx) => [
      idx + 1,
      `"${b.brandName}"`,
      b.pickCount,
      `${b.percentage}%`,
      `"${b.topModel}"`,
      b.avgBudget,
      `${b.growthRate}%`,
      `"${(b.popularInProgrammes || []).map((p) => `${p.programmeName} (${p.count})`).join(', ')}"`,
    ]);

    const csvContent = 'data:text/csv;charset=utf-8,' + [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `uow_popular_picks_ranks_${period}_${Date.now()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const hasPicks = (reportData?.totalPicks || 0) > 0;

  return (
    <div className="max-w-[1550px] w-full mx-auto space-y-6 pb-12">
      {/* Top Header Card */}
      <div className="bg-white dark:bg-slate-900 p-6 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl sm:text-2xl font-extrabold text-slate-900 dark:text-white flex items-center space-x-2.5">
            <Layers className="w-6 h-6 text-indigo-600 dark:text-indigo-400" />
            <span>Brands & Popular Picks</span>
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1">
            Student brand preference ranks, top chosen models, and official manufacturer store directories.
          </p>
        </div>

        {/* Action Controls & Timeframe Selector */}
        <div className="flex flex-wrap items-center gap-2">
          {/* Timeframe selector */}
          <div className="bg-slate-100 dark:bg-slate-800 p-1 rounded-xl flex items-center space-x-1 border border-slate-200 dark:border-slate-700">
            <button
              type="button"
              onClick={() => setPeriod('weekly')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer flex items-center space-x-1.5 ${
                period === 'weekly'
                  ? 'bg-blue-600 text-white shadow-xs'
                  : 'text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white'
              }`}
            >
              <Calendar className="w-3.5 h-3.5" />
              <span>Weekly</span>
            </button>
            <button
              type="button"
              onClick={() => setPeriod('monthly')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer flex items-center space-x-1.5 ${
                period === 'monthly'
                  ? 'bg-blue-600 text-white shadow-xs'
                  : 'text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white'
              }`}
            >
              <Calendar className="w-3.5 h-3.5" />
              <span>Monthly</span>
            </button>
            <button
              type="button"
              onClick={() => setPeriod('all')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer flex items-center space-x-1.5 ${
                period === 'all'
                  ? 'bg-blue-600 text-white shadow-xs'
                  : 'text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white'
              }`}
            >
              <Layers className="w-3.5 h-3.5" />
              <span>All-Time</span>
            </button>
          </div>

          {/* Programme Filter Dropdown */}
          <div className="flex items-center space-x-1.5 bg-slate-50 dark:bg-slate-800 px-3 py-1.5 rounded-xl border border-slate-200 dark:border-slate-700">
            <Filter className="w-3.5 h-3.5 text-slate-500" />
            <select
              value={selectedProgrammeId}
              onChange={(e) => setSelectedProgrammeId(e.target.value)}
              className="bg-transparent text-xs font-medium text-slate-800 dark:text-slate-200 focus:outline-hidden cursor-pointer"
            >
              <option value="all" className="bg-white dark:bg-slate-900">All Programmes</option>
              {allProgrammes.map((p) => (
                <option key={p.id} value={p.id} className="bg-white dark:bg-slate-900">
                  {p.code}
                </option>
              ))}
            </select>
          </div>

          {/* Copy Summary */}
          <button
            type="button"
            onClick={handleCopySummary}
            className="p-2 sm:px-3 sm:py-1.5 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 text-xs font-semibold border border-slate-200 dark:border-slate-700 transition-all cursor-pointer flex items-center space-x-1.5"
            title="Copy summary"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5 text-slate-500" />}
            <span className="hidden sm:inline">{copied ? 'Copied!' : 'Copy'}</span>
          </button>

          {/* Export CSV */}
          <button
            type="button"
            onClick={handleExportCSV}
            className="p-2 sm:px-3 sm:py-1.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold shadow-xs transition-all cursor-pointer flex items-center space-x-1.5"
            title="Export CSV"
          >
            <Download className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">Export CSV</span>
          </button>

          {/* Reset to 0 */}
          <button
            type="button"
            onClick={handleResetToZero}
            disabled={isResetting}
            className="p-2 sm:px-3 sm:py-1.5 rounded-xl bg-rose-50 dark:bg-rose-950/60 hover:bg-rose-100 dark:hover:bg-rose-900/60 text-rose-600 dark:text-rose-400 text-xs font-bold border border-rose-200 dark:border-rose-800/80 transition-all cursor-pointer flex items-center space-x-1.5"
            title="Reset picks to zero"
          >
            <RotateCcw className={`w-3.5 h-3.5 ${isResetting ? 'animate-spin' : ''}`} />
            <span className="hidden sm:inline">{resetSuccess ? 'Reset!' : 'Reset'}</span>
          </button>

          <button
            type="button"
            onClick={fetchReport}
            className="p-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-500 hover:text-slate-900 dark:hover:text-white transition-all"
            title="Refresh data"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isLoading ? 'animate-spin' : ''}`} />
          </button>
        </div>
      </div>

      {/* Popular Picks Ranks Table Section */}
      <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-xs overflow-hidden">
        <div className="p-5 border-b border-slate-100 dark:border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <div>
            <h2 className="font-bold text-base sm:text-lg text-slate-900 dark:text-white flex items-center space-x-2">
              <span className="w-2.5 h-2.5 rounded-full bg-blue-600"></span>
              <span>Popular Picks Ranks</span>
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Ranked list of laptop brands by student picks, top chosen models, average budgets, and programme.
            </p>
          </div>

          <div className="flex items-center space-x-2 text-xs font-semibold text-slate-500 dark:text-slate-400">
            <span className="px-2.5 py-1 bg-slate-100 dark:bg-slate-800 rounded-lg">
              Total Picks: <strong className="text-slate-900 dark:text-white font-mono">{reportData?.totalPicks || 0}</strong>
            </span>
            <span className="px-2.5 py-1 bg-blue-50 dark:bg-blue-950/60 text-blue-700 dark:text-blue-300 rounded-lg">
              {reportData?.periodLabel || 'Weekly'}
            </span>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50 dark:bg-slate-800/60 border-b border-slate-200 dark:border-slate-800 text-[11px] uppercase tracking-wider text-slate-500 dark:text-slate-400 font-bold">
                <th className="py-3.5 px-4 text-center w-12">Rank</th>
                <th className="py-3.5 px-4">Brand</th>
                <th className="py-3.5 px-4 text-center">Picks Volume</th>
                <th className="py-3.5 px-4">Market Share</th>
                <th className="py-3.5 px-4">Top Picked Model</th>
                <th className="py-3.5 px-4">Avg Student Budget</th>
                <th className="py-3.5 px-4">Programme</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800 text-xs">
              {(reportData?.brands || []).map((brand, idx) => (
                <tr
                  key={brand.brandId}
                  className="hover:bg-slate-50/70 dark:hover:bg-slate-800/40 transition-colors"
                >
                  <td className="py-4 px-4 text-center">
                    <span
                      className={`inline-flex items-center justify-center w-6 h-6 rounded-full font-bold text-xs ${
                        hasPicks && idx === 0
                          ? 'bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300'
                          : hasPicks && idx === 1
                          ? 'bg-slate-200 text-slate-700 dark:bg-slate-700 dark:text-slate-200'
                          : hasPicks && idx === 2
                          ? 'bg-orange-100 text-orange-700 dark:bg-orange-950 dark:text-orange-300'
                          : 'text-slate-500 bg-slate-100 dark:bg-slate-800'
                      }`}
                    >
                      {idx + 1}
                    </span>
                  </td>

                  <td className="py-4 px-4">
                    <div className="flex items-center space-x-2.5">
                      <div
                        className="w-3 h-3 rounded-full shrink-0"
                        style={{ backgroundColor: BRAND_COLORS[idx % BRAND_COLORS.length] }}
                      ></div>
                      <div>
                        <span className="font-bold text-slate-900 dark:text-white block">
                          {brand.brandName}
                        </span>
                        <span className="text-[11px] text-slate-500 dark:text-slate-400 font-medium">
                          {brand.growthRate !== 0 ? `${brand.growthRate >= 0 ? '+' : ''}${brand.growthRate}% vs prior` : '0% growth'}
                        </span>
                      </div>
                    </div>
                  </td>

                  <td className="py-4 px-4 text-center">
                    <span className="font-extrabold text-sm text-slate-900 dark:text-white font-mono">
                      {brand.pickCount}
                    </span>
                    <span className="text-[10px] text-slate-400 block">selections</span>
                  </td>

                  <td className="py-4 px-4 min-w-[150px]">
                    <div className="space-y-1">
                      <div className="flex items-center justify-between text-xs">
                        <span className="font-bold text-slate-800 dark:text-slate-200">{brand.percentage}%</span>
                      </div>
                      <div className="w-full bg-slate-100 dark:bg-slate-800 h-2 rounded-full overflow-hidden">
                        <div
                          className="h-full rounded-full transition-all duration-500"
                          style={{
                            width: `${Math.min(100, brand.percentage * 2.5)}%`,
                            backgroundColor: BRAND_COLORS[idx % BRAND_COLORS.length],
                          }}
                        ></div>
                      </div>
                    </div>
                  </td>

                  <td className="py-4 px-4">
                    <div className="flex items-center space-x-1.5">
                      <Laptop className="w-3.5 h-3.5 text-blue-500 shrink-0" />
                      <span className="font-semibold text-slate-800 dark:text-slate-200 truncate max-w-[200px]">
                        {brand.topModel || 'N/A'}
                      </span>
                    </div>
                  </td>

                  <td className="py-4 px-4 font-mono font-semibold text-slate-800 dark:text-slate-200">
                    RM {brand.avgBudget.toLocaleString()}
                  </td>

                  <td className="py-4 px-4">
                    {brand.popularInProgrammes && brand.popularInProgrammes.length > 0 ? (
                      <div className="flex flex-wrap gap-1 max-w-xs">
                        {brand.popularInProgrammes.map((p, pIdx) => (
                          <span
                            key={pIdx}
                            className="text-[10px] px-2 py-0.5 rounded-md bg-blue-50 dark:bg-blue-950/70 text-blue-700 dark:text-blue-300 font-medium border border-blue-200/60 dark:border-blue-800/60"
                          >
                            {p.programmeName.replace('Bachelor of Computer Science (Hons) in ', 'BCS: ').replace('Bachelor of Information Technology (Hons) in ', 'BIT: ')}
                          </span>
                        ))}
                      </div>
                    ) : (
                      <span className="text-[11px] text-slate-400 italic">No programme data yet</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Brand Directory / Hardware Manufacturers Section */}
      <div className="bg-white dark:bg-slate-900 p-6 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-xs space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="font-bold text-base sm:text-lg text-slate-900 dark:text-white flex items-center space-x-2">
              <Store className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
              <span>Hardware Manufacturers & Brand Directory</span>
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Verified laptop partner brands and official hardware store links.
            </p>
          </div>
          <span className="text-xs font-semibold text-slate-500 px-3 py-1 bg-slate-100 dark:bg-slate-800 rounded-lg">
            {brands.length} Verified Brands
          </span>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4 pt-2">
          {brands.map((b, idx) => (
            <div
              key={b.id}
              className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700/80 shadow-2xs space-y-2 hover:border-blue-400 dark:hover:border-blue-500 transition-all"
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <div
                    className="w-2.5 h-2.5 rounded-full shrink-0"
                    style={{ backgroundColor: BRAND_COLORS[idx % BRAND_COLORS.length] }}
                  ></div>
                  <h3 className="font-bold text-sm text-slate-900 dark:text-white">{b.name}</h3>
                </div>
                <span className="text-[10px] uppercase font-bold text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900 px-1.5 py-0.5 rounded border border-slate-200 dark:border-slate-700">
                  OEM Partner
                </span>
              </div>
              {b.website_url && (
                <a
                  href={b.website_url}
                  target="_blank"
                  rel="noreferrer"
                  className="text-xs text-blue-600 dark:text-blue-400 flex items-center space-x-1 hover:underline pt-1"
                >
                  <span>Official Store</span>
                  <ExternalLink className="w-3 h-3" />
                </a>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

// Re-export as BrandPopularityReport for backward compatibility
export const BrandPopularityReport = BrandManagement;
